services:
  borg-server:
    build:
      context: .
      platforms:
        #- "linux/arm64"
        - "linux/amd64"
    restart: always
    image: workleast/borg-server
    container_name: borg-server
    volumes:
      - ${REPO_DIR}:/backups
      - ${SSH_DIR}:/home/borg/.ssh
    ports:
      - "2022:22"
