services:
  borg-server:
    restart: always
    image: workleast/borg-server
    container_name: borg-server
    volumes:
      - path/to/repository:/backups
      - ./ssh/authorized_keys:/home/borg/.ssh/authorized_keys
    ports:
      - "2022:22"
    environment:
      TZ: "Asia/Ho_Chi_Minh"
